@extends('layouts.app')

@section('title', 'Lacak Servis — Defkan Computer')

@section('content')
<div class="container page-container" style="max-width: 1000px;">
    
    {{-- Header --}}
    <div class="page-header-center" style="margin-bottom: 40px; text-align: center;">
        <div style="width: 56px; height: 56px; background: var(--primary-light); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px;">
            <i data-lucide="crosshair" style="width: 28px; height: 28px; color: var(--primary);"></i>
        </div>
        <h1 style="font-weight: 800; font-size: 36px; margin-bottom: 16px;">Lacak Servis Anda</h1>
        <p class="text-muted" style="max-width: 600px; margin: 0 auto; font-size: 15px; line-height: 1.6;">
            Masukkan kode servis atau nomor tanda terima untuk mengetahui status perbaikan perangkat Anda secara real-time.
        </p>
    </div>

    {{-- Search Bar --}}
    <div class="glass-panel" style="max-width: 600px; margin: 0 auto 40px; padding: 12px 12px 12px 24px; display: flex; align-items: center; border-radius: 12px;">
        <i data-lucide="hash" style="color: var(--text-subtle); margin-right: 12px;"></i>
        <input type="text" id="track-code" placeholder="SRV-2023-0981" style="flex: 1; border: none; outline: none; background: transparent; font-size: 16px; color: var(--text-main); font-weight: 500; text-transform: uppercase;">
        <button id="btn-track" onclick="handleTrackServis()" class="btn btn-primary" style="padding: 14px 28px; border-radius: 8px;">Lacak Servis</button>
    </div>

    {{-- Tracking Result Area --}}
    <div id="track-result" style="display: none; grid-template-columns: 1.2fr 1fr; gap: 24px; align-items: start;">
        
        {{-- Kiri: Status Saat Ini --}}
        <div class="glass-panel" style="padding: 32px;">
            <h3 style="font-size: 18px; font-weight: 700; margin-bottom: 40px;">Status Saat Ini</h3>
            
            <div class="stepper-container" style="position: relative; display: flex; justify-content: space-between;">
                <!-- Connecting Line Base -->
                <div style="position: absolute; top: 20px; left: 10%; right: 10%; height: 3px; background: var(--glass-border); z-index: 0;"></div>
                <!-- Connecting Line Active (width varies) -->
                <div id="step-progress-bar" style="position: absolute; top: 20px; left: 10%; width: 0%; height: 3px; background: var(--primary); z-index: 1; transition: width 0.4s ease;"></div>

                <!-- Steps will be generated by JS -->
                <div class="step-item" id="step-1" style="position: relative; z-index: 2; display: flex; flex-direction: column; align-items: center; gap: 12px; flex: 1;">
                    <div class="step-icon" style="width: 44px; height: 44px; border-radius: 50%; background: var(--primary); color: white; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 12px rgba(37,99,235,0.3);">
                        <i data-lucide="clock" class="icon icon-sm"></i>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size: 12px; font-weight: 700; color: var(--text-main);">Menunggu</div>
                        <div class="step-date" style="font-size: 11px; color: var(--text-muted); margin-top: 2px; display: none;"></div>
                    </div>
                </div>

                <div class="step-item" id="step-2" style="position: relative; z-index: 2; display: flex; flex-direction: column; align-items: center; gap: 12px; flex: 1;">
                    <div class="step-icon" style="width: 44px; height: 44px; border-radius: 50%; background: var(--bg-surface); border: 2px solid var(--glass-border); color: var(--text-subtle); display: flex; align-items: center; justify-content: center;">
                        <i data-lucide="search" class="icon icon-sm"></i>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size: 12px; font-weight: 600; color: var(--text-subtle);">Diperiksa</div>
                        <div class="step-date" style="font-size: 11px; color: var(--text-muted); margin-top: 2px; display: none;"></div>
                    </div>
                </div>

                <div class="step-item" id="step-3" style="position: relative; z-index: 2; display: flex; flex-direction: column; align-items: center; gap: 12px; flex: 1;">
                    <div class="step-icon" style="width: 44px; height: 44px; border-radius: 50%; background: var(--bg-surface); border: 2px solid var(--glass-border); color: var(--text-subtle); display: flex; align-items: center; justify-content: center;">
                        <i data-lucide="wrench" class="icon icon-sm"></i>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size: 12px; font-weight: 600; color: var(--text-subtle);">Dikerjakan</div>
                        <div class="step-date" style="font-size: 11px; color: var(--text-muted); margin-top: 2px; display: none;"></div>
                    </div>
                </div>

                <div class="step-item" id="step-4" style="position: relative; z-index: 2; display: flex; flex-direction: column; align-items: center; gap: 12px; flex: 1;">
                    <div class="step-icon" style="width: 44px; height: 44px; border-radius: 50%; background: var(--bg-surface); border: 2px solid var(--glass-border); color: var(--text-subtle); display: flex; align-items: center; justify-content: center;">
                        <i data-lucide="check-circle-2" class="icon icon-sm"></i>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size: 12px; font-weight: 600; color: var(--text-subtle);">Selesai</div>
                        <div class="step-date" style="font-size: 11px; color: var(--text-muted); margin-top: 2px; display: none;"></div>
                    </div>
                </div>

                <div class="step-item" id="step-5" style="position: relative; z-index: 2; display: flex; flex-direction: column; align-items: center; gap: 12px; flex: 1;">
                    <div class="step-icon" style="width: 44px; height: 44px; border-radius: 50%; background: var(--bg-surface); border: 2px solid var(--glass-border); color: var(--text-subtle); display: flex; align-items: center; justify-content: center;">
                        <i data-lucide="package" class="icon icon-sm"></i>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size: 12px; font-weight: 600; color: var(--text-subtle);">Diambil</div>
                        <div class="step-date" style="font-size: 11px; color: var(--text-muted); margin-top: 2px; display: none;"></div>
                    </div>
                </div>
            </div>
            
            <div style="margin-top: 40px; padding-top: 24px; border-top: 1px solid var(--glass-border); display: flex; justify-content: space-between; align-items: center;">
                <div style="font-size: 13.5px; color: var(--text-muted);">Estimasi Pengerjaan:</div>
                <div id="res-durasi" style="font-size: 14px; font-weight: 600; color: var(--text-main);">Akan dikonfirmasi</div>
            </div>
        </div>

        {{-- Kanan: Detail Tiket --}}
        <div class="glass-panel" style="padding: 32px;">
            <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px;">
                <h3 style="font-size: 18px; font-weight: 700;">Detail Tiket</h3>
                <div id="res-kode-badge" style="background: var(--primary); color: white; font-size: 11px; font-weight: 600; padding: 4px 12px; border-radius: 20px;">SRV-...</div>
            </div>

            <div style="display: flex; flex-direction: column; gap: 16px;">
                
                <div>
                    <div style="font-size: 10px; font-weight: 700; color: var(--text-subtle); letter-spacing: 0.5px; text-transform: uppercase; margin-bottom: 4px;">Tipe Laptop</div>
                    <div id="res-merek" style="font-size: 14px; font-weight: 600; color: var(--text-main); display: flex; align-items: center; gap: 8px;">
                        <i data-lucide="laptop" class="icon icon-sm" style="color: var(--primary);"></i> <span>-</span>
                    </div>
                </div>

                <div>
                    <div style="font-size: 10px; font-weight: 700; color: var(--text-subtle); letter-spacing: 0.5px; text-transform: uppercase; margin-bottom: 4px;">Keluhan</div>
                    <div id="res-keluhan" style="font-size: 13px; color: var(--text-muted); background: var(--bg-surface-alt); padding: 12px; border-radius: 8px; line-height: 1.6;">
                        -
                    </div>
                </div>

                <div>
                    <div style="font-size: 10px; font-weight: 700; color: var(--text-subtle); letter-spacing: 0.5px; text-transform: uppercase; margin-bottom: 4px;">Catatan Teknisi</div>
                    <div id="res-catatan" style="font-size: 13px; color: var(--primary); background: var(--primary-light); padding: 12px; border-radius: 8px; line-height: 1.6;">
                        Belum ada catatan.
                    </div>
                </div>

                <div style="margin-top: 12px; display: flex; justify-content: space-between; align-items: flex-end;">
                    <div>
                        <div style="font-size: 12px; color: var(--text-muted);">Estimasi Biaya</div>
                        <div id="res-update-date" style="font-size: 10px; color: var(--text-subtle); margin-top: 2px;">Terakhir update: -</div>
                    </div>
                    <div id="res-biaya" style="font-size: 20px; font-weight: 800; color: var(--text-main);">Menunggu Cek</div>
                </div>

            </div>
        </div>
    </div>
    
    {{-- Not Found --}}
    <div id="track-error" style="display: none; text-align: center; margin-top: 40px;">
        <i data-lucide="file-warning" style="width: 48px; height: 48px; color: var(--danger); margin-bottom: 16px; opacity: 0.8;"></i>
        <h3 style="font-size: 18px; font-weight: 700; margin-bottom: 8px;">Tiket Tidak Ditemukan</h3>
        <p class="text-muted" style="font-size: 14px;">Pastikan kode servis yang Anda masukkan sudah benar.</p>
    </div>

</div>
@endsection

@push('styles')
<style>
@media (max-width: 900px) {
    #track-result {
        grid-template-columns: 1fr !important;
    }
}

@keyframes stepPulse {
    0% {
        box-shadow: 0 0 0 0 rgba(37, 99, 235, 0.5), 0 4px 12px rgba(37, 99, 235, 0.3);
        transform: scale(1);
    }
    50% {
        box-shadow: 0 0 0 10px rgba(37, 99, 235, 0), 0 4px 12px rgba(37, 99, 235, 0.3);
        transform: scale(1.08);
    }
    100% {
        box-shadow: 0 0 0 0 rgba(37, 99, 235, 0), 0 4px 12px rgba(37, 99, 235, 0.3);
        transform: scale(1);
    }
}

.step-current-active {
    animation: stepPulse 2s infinite ease-in-out !important;
    border: 3px solid rgba(255, 255, 255, 0.95) !important;
    outline: 2px solid var(--primary);
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
    // Check if code is in URL
    const params = new URLSearchParams(window.location.search);
    if(params.has('code')) {
        document.getElementById('track-code').value = params.get('code');
        handleTrackServis();
    }
    
    document.getElementById('track-code').addEventListener('keypress', function(e) {
        if(e.key === 'Enter') handleTrackServis();
    });
});

async function handleTrackServis() {
    const code = document.getElementById('track-code').value.trim().toUpperCase();
    const btn = document.getElementById('btn-track');
    const resultDiv = document.getElementById('track-result');
    const errorDiv = document.getElementById('track-error');

    if (!code) {
        showToast('Masukkan kode servis terlebih dahulu', 'error');
        return;
    }

    const origBtnTxt = btn.innerHTML;
    btn.innerHTML = '<div class="loader" style="width:16px; height:16px; border-width:2px; border-top-color: white;"></div>';
    btn.disabled = true;
    
    resultDiv.style.display = 'none';
    errorDiv.style.display = 'none';

    try {
        const res = await apiFetch(`/servis/track/${code}`);
        const data = res.data;

        // Populate detail tiket
        document.getElementById('res-kode-badge').textContent = data.kode_servis;
        document.getElementById('res-merek').innerHTML = `<i data-lucide="laptop" class="icon icon-sm" style="color: var(--primary);"></i> <span>${data.merek_laptop || '-'}</span>`;
        document.getElementById('res-keluhan').textContent = data.deskripsi || '-';
        document.getElementById('res-catatan').textContent = data.keterangan || 'Belum ada catatan tambahan dari teknisi.';
        document.getElementById('res-biaya').textContent = data.estimasi_biaya ? formatRupiah(data.estimasi_biaya) : 'Menunggu Cek';
        document.getElementById('res-durasi').textContent = data.estimasi_durasi || 'Akan dikonfirmasi teknisi';
        
        // Date formats
        const tgl = new Date(data.tanggal_masuk);
        const options = { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute:'2-digit' };
        const dateStr = isNaN(tgl) ? '-' : tgl.toLocaleDateString('id-ID', options) + ' WIB';
        
        document.getElementById('res-update-date').textContent = `Terakhir update: ${dateStr}`;

        // Stepper Logic
        // Status enum: menunggu, diperiksa, dikerjakan, selesai, diambil
        const statuses = ['menunggu', 'diperiksa', 'dikerjakan', 'selesai', 'diambil'];
        let currentIndex = statuses.indexOf(data.status?.toLowerCase());
        if(currentIndex === -1) currentIndex = 0; // fallback

        // Progress bar width (4 segments: 0%, 25%, 50%, 75%, 100%)
        const progressWidth = (currentIndex / (statuses.length - 1)) * 100;
        document.getElementById('step-progress-bar').style.width = `${progressWidth}%`;

        // Update each step icon
        statuses.forEach((s, i) => {
            const stepEl = document.getElementById(`step-${i+1}`);
            const iconContainer = stepEl.querySelector('.step-icon');
            const titleEl = stepEl.querySelector('div > div:first-child');
            const dateEl = stepEl.querySelector('.step-date');
            
            if (i <= currentIndex) {
                // Active/Completed
                iconContainer.style.background = 'var(--primary)';
                iconContainer.style.color = 'white';
                iconContainer.style.border = 'none';
                iconContainer.style.boxShadow = '0 4px 12px rgba(37,99,235,0.3)';
                titleEl.style.fontWeight = '700';
                titleEl.style.color = 'var(--text-main)';
                
                if (i === currentIndex) {
                    iconContainer.classList.add('step-current-active');
                } else {
                    iconContainer.classList.remove('step-current-active');
                }
                
                // If it's the current step or first step, show date/time
                if (dateEl) {
                    if (i === 0 || i === currentIndex) {
                        dateEl.textContent = i === 0 ? dateStr.split(' ')[0] : 'Saat Ini';
                        dateEl.style.color = i === currentIndex ? 'var(--primary)' : 'var(--text-muted)';
                        dateEl.style.display = 'block';
                    } else {
                        dateEl.style.display = 'none';
                    }
                }
            } else {
                // Inactive
                iconContainer.style.background = 'var(--bg-surface)';
                iconContainer.style.color = 'var(--text-subtle)';
                iconContainer.style.border = '2px solid var(--glass-border)';
                iconContainer.style.boxShadow = 'none';
                iconContainer.classList.remove('step-current-active');
                titleEl.style.fontWeight = '600';
                titleEl.style.color = 'var(--text-subtle)';
                
                if (dateEl) {
                    dateEl.style.display = 'none';
                }
            }
        });

        // Fade in
        resultDiv.style.display = 'grid';
        lucide.createIcons();

    } catch (err) {
        errorDiv.style.display = 'block';
    } finally {
        btn.innerHTML = origBtnTxt;
        btn.disabled = false;
    }
}
</script>
@endpush
